### ISSUE TITLE
Velikost písma v epubu

### ISSUE THREAD

**Issue by Kedrigern** [pirati-cz/swarmwise-cs#1]
Na některých čtečkách se písmo automaticky zobrazí příliš malé.

Nejspíše souvisí se styly.

Hlášeno pro čtečku: PocketBook Touchpad 2

**Comment by nextghost** [comment]
V CSS stylech jsou stejné velikosti fontů jako v PDF. Minimální velikost hlavního textu je 11pt. Jenom na stránce s licencí je velikost 8pt a ISBN má 10pt. Dá se v té čtečce někde nastavit DPI obrazovky?

**Comment by Alex-007-** [comment]
Na uvedené čtečce se dá běžně nastavovat velikost zobrazovaného textu. To ale v případě zveřejněného ePUBu nefunguje. Musel jsem to prohnat přes Calibre a už to funguje jak má. Sice mi to rozhodilo obsah knihy na začátku, ale zvětšování textu je již bez problémů.

**Comment by nextghost** [comment]
Chtěl bych se podívat na změny, co s tím Calibre udělalo. Můžeš ten upravený EPUB někam nahrát?

Jinak velikost 11pt znamená, že velká písmena by bez zvětšení měla mít na výšku přibližně 3,88mm. Jestli je ta čtečka zobrazuje menší, tak je špatně nastavená systémová hodnota DPI.

**Comment by Alex-007-** [comment]
Poslal jsem ti SZ s detaily. Jinak ten ePUB je zde:
http://uloz.to/xjpoagye/swarmwise-rick-falkvinge-epub

**Comment by Kedrigern** [comment]
IMHO to bude spíš v tom, že jsou ty styly složité a něco to špatně podědí. Popřípadě v písmu. Čtečka se prostě chová dost jinak.

**Comment by nextghost** [comment]
Původní EPUB má velkosti fontů zadané v absolutní jednotkách jako 123pt. Calibre tyhle velikosti v upraveném EPUBu vyházelo a všude je přepsalo na relativní 456em. Čtečka si podle všeho velikosti v absolutních jednotkách vykládá tak, že je nemá zvětšovat. Budu muset překopat CSS styly a všude tam dát relativní jednotky, má to tak být i [podle dokumentace](http://www.idpf.org/accessibility/guidelines/content/style/reference.php).

**Comment by Kedrigern** [comment]
Potvrzuji opravení commitem 6676c13333945eff24ddae73497a01716bc95bbd
